import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import StoreProvider from '@/components/providers/StoreProvider';
import { ToastProvider } from '@/components/providers/ToastProvider';

import { Header } from '@/components/_layout/Header';

import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin', 'cyrillic'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable}`}>
				<div className="wrapper" id="wrapper">
					<StoreProvider>
						<Header />
						<main>{children}</main>
						{/* <Footer data={footerData} /> */}
					</StoreProvider>
					<ToastProvider />
				</div>
			</body>
		</html>
	);
}
